# Generated by Django 5.1.15 on 2026-09-03 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farmers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                (
                    "icon",
                    models.CharField(
                        default="fa-carrot",
                        help_text="FontAwesome icon class",
                        max_length=50,
                    ),
                ),
                ("is_perishable", models.BooleanField(default=True)),
                ("shelf_life_days", models.PositiveIntegerField(default=5)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Crop name, e.g. Fresh Hybrid Tomatoes",
                        max_length=120,
                    ),
                ),
                (
                    "variety",
                    models.CharField(
                        blank=True,
                        help_text="Variety e.g. Abhinav, Kufri Jyoti",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="Freshly harvested produce directly aggregated at village hub.",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("A", "Grade A (Premium / Fresh Pick)"),
                            ("B", "Grade B (Standard Market Grade)"),
                            ("C", "Grade C (Bulk / Processing Grade)"),
                        ],
                        default="A",
                        max_length=2,
                    ),
                ),
                (
                    "available_quantity_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total available stock in kg",
                        max_digits=8,
                    ),
                ),
                (
                    "minimum_order_kg",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=6),
                ),
                (
                    "farmer_base_price_per_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Direct payout received by farmer per kg (in ₹)",
                        max_digits=7,
                    ),
                ),
                (
                    "consumer_price_per_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Final price paid by consumer per kg (in ₹)",
                        max_digits=7,
                    ),
                ),
                (
                    "traditional_market_price_per_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=40.0,
                        help_text="Retail supermarket benchmark price per kg for comparison (in ₹)",
                        max_digits=7,
                    ),
                ),
                ("harvest_date", models.DateField(help_text="Date of harvest")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                (
                    "emoji_icon",
                    models.CharField(
                        default="🍅",
                        help_text="Fallback emoji for quick display",
                        max_length=10,
                    ),
                ),
                ("is_organic", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products.category",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="farmers.farmerprofile",
                    ),
                ),
            ],
        ),
    ]
