# Generated by Django 5.1.15 on 2026-09-03 15:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MarketBenchmarkPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crop_name",
                    models.CharField(
                        help_text="e.g. Tomato, Potato, Onion", max_length=100
                    ),
                ),
                (
                    "mandi_name",
                    models.CharField(
                        help_text="e.g. Ranchi Pandra APMC Mandi", max_length=120
                    ),
                ),
                ("district", models.CharField(default="Ranchi", max_length=100)),
                ("state", models.CharField(default="Jharkhand", max_length=100)),
                (
                    "modal_price_per_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Most common wholesale mandi rate",
                        max_digits=7,
                    ),
                ),
                (
                    "min_price_per_kg",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                (
                    "max_price_per_kg",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                (
                    "retail_estimated_price_per_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Typical consumer supermarket / retail price in nearby urban areas",
                        max_digits=7,
                    ),
                ),
                ("recorded_date", models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-recorded_date", "crop_name"],
            },
        ),
    ]
