# Generated by Django 5.1.15 on 2026-09-03 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(editable=False, max_length=32, unique=True),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "farmer_payout_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                ("delivery_address", models.TextField()),
                ("contact_phone", models.CharField(max_length=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLACED", "Order Placed (ऑर्डर दर्ज)"),
                            (
                                "CONFIRMED",
                                "Aggregated at Village Hub (ग्राम केंद्र में एकत्रित)",
                            ),
                            ("PICKUP_SCHEDULED", "Pickup Scheduled (पिकअप निर्धारित)"),
                            ("IN_TRANSIT", "In Cold Transit (रास्ते में)"),
                            (
                                "OUT_FOR_DELIVERY",
                                "Out for Delivery (वितरण के लिए निकला)",
                            ),
                            ("DELIVERED", "Delivered (वितरित)"),
                            ("CANCELLED", "Cancelled (रद्द)"),
                        ],
                        default="PLACED",
                        max_length=30,
                    ),
                ),
                ("payment_method", models.CharField(default="UPI_MOCK", max_length=30)),
                ("is_paid", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consumer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_kg", models.DecimalField(decimal_places=2, max_digits=7)),
                ("price_per_kg", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "farmer_price_per_kg",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "farmer_subtotal",
                    models.DecimalField(decimal_places=2, max_digits=9),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
