# Generated by Django 5.1.15 on 2026-09-03 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityDispute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            (
                                "SPOILED_TRANSIT",
                                "Spoiled or Bruised in Transit (पारगमन में खराब)",
                            ),
                            ("WEIGHT_SHORTAGE", "Weight Discrepancy (वजन में कमी)"),
                            ("POOR_GRADE", "Grade Lower than Specified (गुणवत्ता में अंतर)"),
                            ("OTHER", "Other Concern (अन्य शिकायत)"),
                        ],
                        default="SPOILED_TRANSIT",
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Explain the quality or transit issue encountered"
                    ),
                ),
                (
                    "refund_amount_requested",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Under Hub Review (समीक्षाधीन)"),
                            (
                                "RESOLVED_REFUNDED",
                                "Approved & Refund Credited (स्वीकृत व रिफंड जारी)",
                            ),
                            ("REJECTED", "Claim Rejected (अस्वीकृत)"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "consumer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filed_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputes",
                        to="orders.order",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disputes",
                        to="orders.orderitem",
                    ),
                ),
            ],
        ),
    ]
