# Generated by Django 5.1.15 on 2026-09-03 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("facilitators", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "land_area_acres",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.5,
                        help_text="Cultivable land area in acres",
                        max_digits=5,
                    ),
                ),
                (
                    "primary_crops",
                    models.CharField(
                        default="Tomato, Potato, Onion",
                        help_text="Major seasonal crops produced",
                        max_length=255,
                    ),
                ),
                (
                    "bank_account_number",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("bank_ifsc", models.CharField(blank=True, max_length=20, null=True)),
                ("upi_id", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "is_assisted_only",
                    models.BooleanField(
                        default=True,
                        help_text="True if farmer relies on VDF/IVR and does not operate smartphone app directly",
                    ),
                ),
                (
                    "total_sales_realization",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Cumulative farmer earnings in Rupees",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facilitator",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Village Digital Facilitator managing this farmer's digital operations",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="farmers",
                        to="facilitators.facilitatorprofile",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farmer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FarmerSMSLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("LISTING_CREATED", "Listing Published (फसल सूची जारी)"),
                            ("ORDER_RECEIVED", "Order Placed (ऑर्डर प्राप्त)"),
                            ("PICKUP_DONE", "Produce Picked Up (फसल उठाई गई)"),
                            (
                                "PAYMENT_REMITTED",
                                "Bank/UPI Payment Received (भुगतान प्राप्त)",
                            ),
                            ("MARKET_ALERT", "Mandi Price Advisory (मंडी भाव सूचना)"),
                        ],
                        default="LISTING_CREATED",
                        max_length=30,
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("message_text", models.TextField()),
                ("is_delivered", models.BooleanField(default=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_logs",
                        to="farmers.farmerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
    ]
