# Generated by Django 5.1.15 on 2026-09-03 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupBuyingPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. Morabadi Sunday 50kg Tomato Bulk Pool",
                        max_length=150,
                    ),
                ),
                (
                    "apartment_cluster",
                    models.CharField(
                        help_text="e.g. Green Acres Society, Morabadi, Ranchi",
                        max_length=180,
                    ),
                ),
                (
                    "target_kg",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=7),
                ),
                (
                    "current_kg",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
                ),
                (
                    "bulk_price_per_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Discounted community bulk price (15% lower than single retail)",
                        max_digits=7,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Pledging Open (भागीदारी जारी)"),
                            ("LOCKED_FULL", "Target Reached & Locked (लक्ष्य पूर्ण)"),
                            ("DISPATCHED", "Batch In Transit (डिस्पैच हुआ)"),
                        ],
                        default="OPEN",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_buying_pools",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupBuyingParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pledged_kg",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=6),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consumer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_pledges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="marketplace.groupbuyingpool",
                    ),
                ),
            ],
        ),
    ]
