# Generated by Django 5.1.15 on 2026-09-09 15:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupbuyingpool",
            name="status",
            field=models.CharField(
                choices=[
                    (
                        "OPEN",
                        "Pledging Open (भागीदारी जारी)",
                    ),
                    (
                        "LOCKED_FULL",
                        "Target Reached & Locked (लक्ष्य पूर्ण)",
                    ),
                    (
                        "DISPATCHED",
                        "Batch In Transit (डिस्पैच हुआ)",
                    ),
                ],
                default="OPEN",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="CustomerReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reviewer_name",
                    models.CharField(
                        help_text="Your name as you want it displayed", max_length=120
                    ),
                ),
                (
                    "reviewer_role",
                    models.CharField(
                        choices=[
                            ("CONSUMER", "Consumer / Khareedaar"),
                            ("FARMER", "Kisan / Farmer"),
                            ("FACILITATOR", "Village Facilitator (VDF)"),
                            ("SOCIETY", "Housing Society Secretary"),
                            ("OTHER", "Other"),
                        ],
                        default="CONSUMER",
                        max_length=30,
                    ),
                ),
                (
                    "reviewer_location",
                    models.CharField(
                        help_text="Village/City, District, State", max_length=150
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=5,
                    ),
                ),
                (
                    "review_text",
                    models.TextField(
                        help_text="Share your experience (max 600 characters)",
                        max_length=600,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Only approved reviews appear on homepage",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Show in hero testimonials section"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
    ]
