# Generated by Django 5.1.15 on 2026-10-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_alter_groupbuyingpool_status_customerreview"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupbuyingparticipant",
            options={
                "ordering": ["-joined_at"],
                "verbose_name": "Group Buying Participant",
                "verbose_name_plural": "Group Buying Participants",
            },
        ),
        migrations.AlterModelOptions(
            name="groupbuyingpool",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Group Buying Pool",
                "verbose_name_plural": "Group Buying Pools",
            },
        ),
        migrations.AddField(
            model_name="groupbuyingparticipant",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLEDGED", "Pledged (भागीदारी दर्ज)"),
                    ("CONFIRMED", "Confirmed (पुष्ट)"),
                    ("FULFILLED", "Fulfilled / Delivered (वितरित)"),
                    ("CANCELLED", "Cancelled (रद्द)"),
                ],
                default="PLEDGED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="groupbuyingpool",
            name="dispatch_time",
            field=models.CharField(
                default="Today 6 PM", help_text="e.g. Today 6 PM", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="groupbuyingpool",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
