# Generated by Django 5.1.15 on 2026-09-03 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FacilitatorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "village_name",
                    models.CharField(
                        help_text="Primary village assigned to this VDF", max_length=120
                    ),
                ),
                (
                    "center_name",
                    models.CharField(
                        help_text="Name of CSC Center or Village Hub", max_length=150
                    ),
                ),
                (
                    "assigned_district",
                    models.CharField(default="Ranchi", max_length=100),
                ),
                (
                    "commission_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        help_text="Facilitation & quality grading fee percentage (default 5%)",
                        max_digits=4,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilitator_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
