# Generated by Django 5.1.15 on 2026-09-03 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pickup_hub_name",
                    models.CharField(
                        default="Angara Digital CSC Aggregation Hub", max_length=150
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        default="Tata Ace Cold Chain Mini-Van", max_length=80
                    ),
                ),
                (
                    "vehicle_number",
                    models.CharField(default="JH-01-EF-4921", max_length=30),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("picked_up_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("driver_notes", models.TextField(blank=True, default="")),
                (
                    "delivery_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_assignment",
                        to="orders.order",
                    ),
                ),
            ],
        ),
    ]
